---
title: "GEO_MARKETING"
author: "Santonu  Debnath"
date: "01/01/2022"
output: html_document
---
#STARTING

```{r}
library(pacman)
p_load(sf,raster,purrr,dplyr,spDataLarge,osmdata,tmap,leaflet,sp)

```
#
#DATA_SET_LOADING
```{r}
data=spDataLarge::census_de
summary(data)
```
#
#Data_set_creation
```{r}

data=mutate_all(data,list(~ifelse(. %in% c(-1, -9), NA, .)))
data2=select(data,LONG=x_mp_1km,LAT=y_mp_1km,Population=Einwohner,
             Women=Frauen_A,men=Alter_D,House_size=HHGroesse_D)
summary(data2)
```
#
#CREATING RASTER LAYER FROM data_frame
```{r}
crs_codes = rgdal::make_EPSG()[1:2]
dplyr::filter(crs_codes, code == 3035)

geo_market=rasterFromXYZ(data2,crs=st_crs(3035)$proj4string)
geo_market
plot(geo_market)

```
#
#RE_CLASSIFICATION OF LAYERS BASED ON REQ
```{r}

re_Pop=matrix(c(1, 1, 127, 2, 2, 375, 3, 3, 1250,
4, 4, 3000, 5, 5, 6000, 6, 6, 8000),ncol = 3,byrow = TRUE)

re_Women=matrix(c(1, 1, 3, 2, 2,0, 3, 3, 0,
4, 4, 0, 5, 5,0),ncol = 3,byrow = TRUE)

re_Men=matrix(c(1, 1, 3, 2, 2, 0, 3, 5, 0),ncol = 3,byrow = TRUE)

re_House=re_Women

re_cl=list(re_Pop,re_Women,re_Men,re_House) 



reclass =geo_market
for (i in seq_len(nlayers(reclass))) {
reclass[[i]] = reclassify(x = reclass[[i]], rcl = re_cl[[i]], right = NA)
}
names(reclass) = names(geo_market)
reclass
```
#
#RASTER AREA DEFINED
```{r}
population_agg=aggregate(reclass$Population,fact=30,fun=sum) 

#ONLY THE PIXEL THAT MEETS CONDITION ARE SELECTED
#drop=FALSE------->PRESERVES RASTER
population_agg=population_agg[population_agg>500000,drop=FALSE]
plot(population_agg)

```
#
#GROUPING SMALL PIEXELS
```{r}
#GROUPING SMALL PIEXELS
#MAKING IT AS A POLYGON------------>SF_OBJECT
poly_population=population_agg %>% 
                clump() %>% 
                rasterToPolygons() %>% 
                st_as_sf()

#ADDING CLOSE CONNECTED PIXELS
Metro_city=poly_population %>% 
          group_by(clumps) %>% 
          summarise()

Metro_city$clumps
plot(poly_population)
plot(Metro_city)
```
#
#Transforming_coordinates
```{r}
#Transforming_coordinators
metro_city_1=st_transform(Metro_city,4326)
class(metro_city_1)

#Extracts coordinates from each centroid
coordinae=st_centroid(metro_city_1) %>% 
             st_coordinates() %>% 
             round(3)
coordinae1=as.data.frame(coordinae)
coordinae=coordinae1[,1:ncol(coordinae1)]
coordinae=st_as_sf(coordinae,coords = c("X", "Y"), crs = 4326)
plot(metro_city_1)
class(coordinae)

```

#
#Visualization map
#
#tmap_view
```{r}
tmap_mode("view")

qtm(coordinae,fill="IMPORTANT_LOCATIONS",text.size = "AREA")+
  tm_grid()+
  tm_graticules()+
  tm_layout()+
  tmap_options(qtm.minimap = FALSE,show.messages =FALSE)+
  tm_style("gray")+
  tm_minimap(position =c("right","top"))+
  tm_mouse_coordinates()+
  tm_scale_bar(text.size = 2,text.color = "green",
                color.dark = "black",
                color.light = "white")+
  tm_xlab("Longitude")+
  tm_ylab("latitude")

```

#
#TMAP_LEAFLET
```{r}
tmap_mode("plot")

m1=tm_shape(coordinae)+
  tm_bubbles(col="red")+
  tm_scale_bar(position=c("left", "bottom"))+
  tm_compass(type ="radar",position = c("left","top"),show.labels=3)+
  tm_style("gray")+
  tm_layout(bg.color="purple")+
  tm_facets()+
  tm_xlab("Longitude")+
  tm_ylab("latitude")

lf <- tmap_leaflet(m1)
# show leaflet widget
lf


```
#
#ONLY WITH LEAFLET
```{r}
coordinae %>% 
  leaflet() %>% 
  addTiles()  %>% 
  addProviderTiles(provider ="Esri.OceanBasemap",group ="OceanBasemap") %>% 
  addLayersControl(baseGroups = c("OpenStreetMap", "Toner by Stamen","HERE.normalDay"),
                  overlayGroups = c("Markers")) %>% 
  addControl(position =c("topleft"),html = "IMPORTANT AREAS") %>% 
  #addMarkers() %>%
  addLabelOnlyMarkers() %>% 
  # addCircles(radius = 2000,
  #            group = c("normalDay","OceanBasemap"),
  #            label = d1$d1,
  #            opacity = 0.7,
  #            color = "red"
  #            )+
  addCircleMarkers(opacity = 0.7,color = "red") 

```








